// This file is automatically generated. Do not edit it directly
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jesrphdemwfnjakxteeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implc3JwaGRlbXdmbmpha3h0ZWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDkxNzEsImV4cCI6MjA2MjQ4NTE3MX0.9WFUksByeCotKFraCY85rJ6sokrgnrO1JHE7yVQDZT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
